// Import the createCache function from the @emotion/cache package.
// Emotion's cache helps to manage and optimize the CSS generated by Emotion for styling.
import createCache, { EmotionCache } from "@emotion/cache";

/**
 * Creates a new Emotion cache instance.
 *
 * This function sets up a custom cache configuration to manage Emotion-generated styles.
 * Using a custom cache allows for more control over how and where the styles are injected in the DOM.
 *
 * @returns {EmotionCache} - A new Emotion cache instance with the specified configuration.
 *
 * Options:
 * - key: 'css' - This sets a prefix for all generated CSS class names. It helps avoid naming collisions.
 * - prepend: true - Ensures that Emotion's styles are injected at the beginning of the <head> tag,
 *   so they take precedence over other styles, maintaining their specificity.
 */
export default function createEmotionCache(): EmotionCache {
	return createCache({ key: "css", prepend: true });
}
